{% set name = "jaraco.functools" %}
{% set version = "4.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jaraco_functools-{{ version }}.tar.gz
  sha256: be634abfccabce56fa3053f8c7ebe37b682683a4ee7793670ced17bab0087353

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm >=3.4.1
    - setuptools
    - toml
  run:
    - python >={{ python_min }}
    - more-itertools

test:
  requires:
    - python {{ python_min }}
  imports:
    - jaraco.functools

about:
  home: https://github.com/jaraco/jaraco.functools
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Additional functools in the spirit of stdlib's functools.
  doc_url: https://github.com/jaraco/jaraco.functools
  dev_url: https://github.com/jaraco/jaraco.functools

extra:
  recipe-maintainers:
    - carlodri
