appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ivkjyOLgUbkWuQzLQ+fDsS20s70LQzYjMzz8StgLWNIRvszIfE/W7ylRB8xAfKJPI3tI+HZlzclKL1CSsBtEeyvfj5J1eZjGbvjL9h9cjaLOXtSb6mPwOmd0c0Rhs6ALh8EYerUOydhaaC8gIPrM80G4pCLKoqNW7MhGhRYCj94wjxUbORDbP7sOEtS4plHXRQzfPLGt2awjAFP1y6NNqrSRE7mcge170AEEB9m8XO88xAuH1aLMyiXL57aEKDXCIzhARKWgTe1pi/LAYDia4AkHO4sKlTSxHAaek1TMspftHeYY3a0MfNBZ7nEBzgWO24iJYvFiX/x8kq/4GPrevCqdiGs1kL7vK0BCIxC4qsnCBuYS5+FYF9Z22wmNXFwip3ySa4i3sSovwmh5bTHEbmkX/qxo+LbyDkzgEOz7LW++qRLKgBLjtOKfjAGEwig8isBmrzpHpAOl9i+usQVYyYCSjYu+A3myZ7wcZYI0PahW1werCzJ2cbr1HVuybALLyhpA63r/QRazjXodHphFp42EcHYKVLNXeV9rzHV1uLGnmCqsWL/8Am235yGdltR+OgMraeEebhJXcxVi9AJGZM3oQaIlXCFeU1r/YKzPOpB82tAN/Vp5Oxl0u5yDcgVJ76XMbVtj2b9ym2yJgiSjd0BiUKcHsI6oBWIyoHidOwM=}
